[GLOBAL]
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.mixed_interpreter_constraints",
    "pants.backend.python.typecheck.mypy",
]
pants_version = "2.19.0"
remote_cache_read = true
remote_cache_rpc_timeout_millis = 60000
remote_cache_write = true
remote_instance_name = "main"
remote_store_address = "grpc://framework-ci-balancer-1983728860.us-east-1.elb.amazonaws.com:9092"
remote_store_rpc_timeout_millis = 60000
session_end_tasks_timeout = 60.0
unmatched_build_file_globs = "error"

[black]
config = "./pyproject.toml"

[python]
interpreter_constraints = ["==3.10.*", "==3.11.*", "==3.12.*", "==3.9.*"]

[python-infer]
ambiguity_resolution = "by_source_root"

[source]
marker_filenames = ["pyproject.toml"]
root_patterns = ["*tests", "/"]
