[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "fastembed>=0.2.5,<0.3",
    "ipython==8.10.0",
    "jupyter>=1.0.0,<2",
    "mypy==0.991",
    "pre-commit==3.2.0",
    "pylint==2.15.10",
    "pytest==7.2.1",
    "pytest-asyncio",
    "pytest-mock==3.11.1",
    "ruff==0.0.292",
    "tree-sitter-languages>=1.8.0,<2",
    "types-Deprecated>=0.1.0",
    "types-PyYAML>=6.0.12.12,<7",
    "types-protobuf>=4.24.0.4,<5",
    "types-redis==4.5.5.0",
    "types-requests==2.28.11.8",
    "types-setuptools==67.1.0.0",
    "black[jupyter]<=23.9.1,>=23.7.0",
    "codespell[toml]>=v2.2.6",
]

[project]
name = "llama-index-vector-stores-ApertureDB"
version = "0.0.1"
description = "llama-index vector_stores ApertureDB integration"
authors = [{name = "ApertureData", email = "team@aperturedata.io"}]
requires-python = ">=3.9,<3.13"
readme = "README.md"
license = "MIT"
dependencies = [
    "aperturedb>=0.4.36",
    "grpcio>=1.60.0,<2",
    "llama-index-core>=0.12.0,<0.13",
]

[project.optional-dependencies]
fastembed = []

[tool.codespell]
check-filenames = true
check-hidden = true
skip = "*.csv,*.html,*.json,*.jsonl,*.pdf,*.txt,*.ipynb"

[tool.hatch.build.targets.sdist]
include = ["llama_index/"]
exclude = ["**/BUILD"]

[tool.hatch.build.targets.wheel]
include = ["llama_index/"]
exclude = ["**/BUILD"]

[tool.llamahub]
contains_example = true
import_path = "llama_index.vector_stores.ApertureDB"

[tool.llamahub.class_authors]
ApertureDBVectorStore = "aperture-data"

[tool.mypy]
disallow_untyped_defs = true
exclude = ["_static", "build", "examples", "notebooks", "venv"]
ignore_missing_imports = true
python_version = "3.8"

[tool.poetry]
authors = ["ApertureData <team@aperturedata.io>"]
description = "llama-index vector_stores ApertureDB integration"
exclude = ["**/BUILD"]
license = "MIT"
name = "llama-index-vector-stores-ApertureDB"
readme = "README.md"
version = "0.0.2"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
aperturedb = ">=0.4.45"
llama-index-core = "^0.12.0"

[tool.poetry.extras]
fastembed = ["fastembed"]

[tool.poetry.group.dev.dependencies]
fastembed = {optional = true, version = "^0.2.5"}
ipython = "8.10.0"
jupyter = "^1.0.0"
mypy = "0.991"
pre-commit = "3.2.0"
pylint = "2.15.10"
pytest = "7.2.1"
pytest-asyncio = "*"
pytest-mock = "3.11.1"
ruff = "0.0.292"
tree-sitter-languages = "^1.8.0"
types-Deprecated = ">=0.1.0"
types-PyYAML = "^6.0.12.12"
types-protobuf = "^4.24.0.4"
types-redis = "4.5.5.0"
types-requests = "2.28.11.8"
types-setuptools = "67.1.0.0"

[tool.poetry.group.dev.dependencies.black]
extras = ["jupyter"]
version = "<=23.9.1,>=23.7.0"

[tool.poetry.group.dev.dependencies.codespell]
extras = ["toml"]
version = ">=v2.2.6"

[[tool.poetry.packages]]
include = "llama_index/"
