[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.codespell]
check-filenames = true
check-hidden = true
skip = "*.csv,*.html,*.json,*.jsonl,*.pdf,*.txt,*.ipynb"

[tool.llamahub]
contains_example = false
import_path = "llama_index.readers.file"

[tool.llamahub.class_authors]
CSVReader = "llama-index"
DocxReader = "thejessezhang"
EpubReader = "Haowjy"
FlatReader = "llama-index"
HTMLTagReader = "llama-index"
HWPReader = "sangwongenip"
IPYNBReader = "FarisHijazi"
ImageCaptionReader = "FarisHijazi"
ImageReader = "ravi03071991"
ImageTabularChartReader = "jon-chuang"
ImageVisionLLMReader = "FarisHijazi"
MarkdownReader = "hursh-desai"
MboxReader = "llama-index"
PDFReader = "ravi03071991"
PagedCSVReader = "thejessezhang"
PandasCSVReader = "ephe-meral"
PandasExcelReader = "denen99"
PptxReader = "thejessezhang"
PyMuPDFReader = "iamarunbrahma"
RTFReader = "FunkyOz"
UnstructuredReader = "thejessezhang"
VideoAudioReader = "llama-index"
XMLReader = "mmaatouk"

[tool.mypy]
disallow_untyped_defs = true
exclude = ["_static", "build", "examples", "notebooks", "venv"]
ignore_missing_imports = true
python_version = "3.8"

[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = "llama-index readers file integration"
exclude = ["**/BUILD"]
keywords = ["10k", "10q", "chart", "eml", "figure", "html", "hwp", "image", "invoice", "ipynb", "jupyter", "notebook", "pdf", "pymupdf", "receipt", "sec", "spreadsheet", "tabular", "unstructured.io", "yaml", "yml"]
license = "MIT"
maintainers = ["FarisHijazi", "Haowjy", "ephe-meral", "hursh-desai", "iamarunbrahma", "jon-chuang", "mmaatouk", "ravi03071991", "sangwongenip", "thejessezhang"]
name = "llama-index-readers-file"
readme = "README.md"
version = "0.2.2"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
# pymupdf is AGPLv3-licensed, so it's optional
pymupdf = {optional = true, version = "^1.23.21"}
beautifulsoup4 = "^4.12.3"
pypdf = "^4.0.1"
striprtf = "^0.0.26"
pandas = "*"
llama-index-core = "^0.11.0"

[tool.poetry.extras]
pymupdf = [
    "pymupdf",
]

[tool.poetry.group.dev.dependencies]
fpdf2 = "2.7.8"
ipython = "8.10.0"
jupyter = "^1.0.0"
mypy = "0.991"
pre-commit = "3.2.0"
pylint = "2.15.10"
pytest = "7.2.1"
pytest-mock = "3.11.1"
ruff = "0.0.292"
tree-sitter-languages = "^1.8.0"
types-Deprecated = ">=0.1.0"
types-PyYAML = "^6.0.12.12"
types-protobuf = "^4.24.0.4"
types-redis = "4.5.5.0"
types-requests = "2.28.11.8"
types-setuptools = "67.1.0.0"

[tool.poetry.group.dev.dependencies.black]
extras = ["jupyter"]
version = "<=23.9.1,>=23.7.0"

[tool.poetry.group.dev.dependencies.codespell]
extras = ["toml"]
version = ">=v2.2.6"

[[tool.poetry.packages]]
include = "llama_index/"
