[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.codespell]
check-filenames = true
check-hidden = true
skip = "*.csv,*.html,*.json,*.jsonl,*.pdf,*.txt,*.ipynb"

[tool.llamahub]
contains_example = false
import_path = "llama_index.readers.google"

[tool.llamahub.class_authors]
GmailReader = "bbornsztein"
GoogleCalendarReader = "ong"
GoogleChatReader = "jonathanhliu21"
GoogleDocsReader = "jerryjliu"
GoogleDriveReader = "ravi03071991"
GoogleKeepReader = "pycui"
GoogleMapsTextSearchReader = "ovuruska"
GoogleSheetsReader = "piroz"

[tool.llamahub.class_contributors]
GoogleDriveReader = ["metanov"]

[tool.mypy]
disallow_untyped_defs = true
exclude = ["_static", "build", "examples", "notebooks", "venv"]
ignore_missing_imports = true
python_version = "3.8"

[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = "llama-index readers google integration"
exclude = ["**/BUILD"]
keywords = ["email", "gmail", "google keep", "google maps", "google notes"]
license = "MIT"
maintainers = [
    "bbornsztein",
    "jerryjliu",
    "metanov",
    "ong",
    "piroz",
    "pycui",
    "ravi03071991",
]
name = "llama-index-readers-google"
readme = "README.md"
version = "0.4.1"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
google-api-python-client = "^2.115.0"
google-auth-httplib2 = "^0.2.0"
google-auth-oauthlib = "^1.2.0"
pydrive = "^1.3.1"
gkeepapi = "^0.15.1"
pandas = "*"
llama-index-core = "^0.11.0"

[tool.poetry.group.dev.dependencies]
ipython = "8.10.0"
jupyter = "^1.0.0"
mypy = "0.991"
pre-commit = "3.2.0"
pylint = "2.15.10"
pytest = "7.2.1"
pytest-mock = "3.11.1"
ruff = "0.0.292"
tree-sitter-languages = "^1.8.0"
types-Deprecated = ">=0.1.0"
types-PyYAML = "^6.0.12.12"
types-protobuf = "^4.24.0.4"
types-redis = "4.5.5.0"
types-requests = "2.28.11.8"
types-setuptools = "67.1.0.0"

[tool.poetry.group.dev.dependencies.black]
extras = ["jupyter"]
version = "<=23.9.1,>=23.7.0"

[tool.poetry.group.dev.dependencies.codespell]
extras = ["toml"]
version = ">=v2.2.6"

[[tool.poetry.packages]]
include = "llama_index/"
