[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "black>=24.3.0",
    "diff-cover>=9.2.4",
    "mypy>=1.11.0",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "pytest-cov>=6.1.1",
    "ruff==0.11.11",
]

[project]
name = "llama-index-readers-massive"
version = "0.1.0"
description = "llama-index readers massive web integration"
readme = "README.md"
requires-python = ">=3.10,<4.0"
license = "MIT"
authors = [
    {name = "Valentyn Naboka", email = "valentin@joinmassive.com"},
]
dependencies = [
    "beautifulsoup4>=4.12.0",
    "llama-index-core>=0.12.0",
    "playwright>=1.40.0",
]

[tool.codespell]
check-filenames = true
check-hidden = true
skip = "*.csv,*.html,*.json,*.jsonl,*.pdf,*.txt,*.ipynb"

[tool.hatch.build.targets.sdist]
include = ["llama_index/"]
exclude = ["**/BUILD"]

[tool.hatch.build.targets.wheel]
include = ["llama_index/"]
exclude = ["**/BUILD"]

[tool.llamahub]
contains_example = false
import_path = "llama_index.readers.massive"

[tool.llamahub.class_authors]
MassiveWebReader = "ValentynNaboka"

[tool.mypy]
disallow_untyped_defs = true
exclude = ["_static", "build", "examples", "notebooks", "venv"]
ignore_missing_imports = true
python_version = "3.10"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
asyncio_mode = "auto"
markers = [
    "integration: marks integration tests",
    "unit: marks unit tests",
]
