[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "contributor-2"
readme = "README.md"
version = "0.2.0"

[tool.poetry.dependencies]
python = ">3.9,<3.12"
llama-index = "^0.12.0"
llama-index-networks = "^0.5.1"
llama-index-packs-diff-private-simple-dataset = "^0.3.0"
