[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "contributor-2"
version = "0.2.0"
description = ""
authors = [{name = "Your Name", email = "you@example.com"}]
requires-python = ">3.9,<3.12"
readme = "README.md"
dependencies = [
    "llama-index>=0.12.0,<0.13",
    "llama-index-networks>=0.5.1,<0.6",
    "llama-index-packs-diff-private-simple-dataset>=0.3.0,<0.4",
]
