[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "contributor-2"
readme = "README.md"
version = "0.2.0"

[tool.poetry.dependencies]
python = "^3.10"
llama-index = "^0.14.0"
llama-index-networks = {allow-prereleases = true, version = "^0.2.1a2"}
llama-index-packs-diff-private-simple-dataset = {allow-prereleases = true, version = "^0.1.0a0"}
