[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "contributor-1"
version = "0.2.1"
description = ""
authors = [{name = "Your Name", email = "you@example.com"}]
requires-python = ">=3.9,<4.0"
dependencies = [
    "llama-index>=0.12.0,<0.13",
    "llama-index-networks>=0.5.1,<0.6",
    "llama-index-llms-openai>=0.4.0,<0.5",
]
