[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "contributor-1"
version = "0.2.0"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
llama-index = "^0.12.0"
llama-index-networks = "^0.5.1"
llama-index-llms-openai = "^0.3.14"
