[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "black[jupyter]<=23.9.1,>=23.7.0",
    "codespell[toml]>=v2.2.6",
    "diff-cover>=9.2.0",
    "ipython==8.10.0",
    "jupyter>=1.0.0,<2",
    "llama-index-vector-stores-duckdb>=0.4.2",
    "mypy==0.991",
    "pre-commit==3.2.0",
    "pyarrow-stubs>=20.0.0.20250627",
    "pylint==2.15.10",
    "pytest-asyncio>=0.23.8",
    "pytest-cov>=6.1.1",
    "pytest-mock==3.11.1",
    "pytest==7.2.1",
    "ruff==0.11.11",
    "types-Deprecated>=0.1.0",
    "types-protobuf>=4.24.0.4,<5",
    "types-PyYAML>=6.0.12.12,<7",
    "types-requests==2.28.11.8",
    "types-setuptools==67.1.0.0",
]

[project]
name = "llama-index-storage-kvstore-duckdb"
version = "0.1.3"
description = "llama-index kvstore duckdb integration"
authors = [{name = "Your Name", email = "you@example.com"}]
requires-python = ">=3.9,<4.0"
readme = "README.md"
license = "MIT"
dependencies = [
    "duckdb>=0.10.1,<1.4.0",
    "llama-index-core>=0.12.0,<0.13",
    "llama-index-vector-stores-duckdb>=0.4.2",
    "pyarrow>=20.0.0",
]

[tool.codespell]
check-filenames = true
check-hidden = true
skip = "*.csv,*.html,*.json,*.jsonl,*.pdf,*.txt,*.ipynb"

[tool.hatch.build.targets.sdist]
include = ["llama_index/"]
exclude = ["**/BUILD"]

[tool.hatch.build.targets.wheel]
include = ["llama_index/"]
exclude = ["**/BUILD"]

[tool.llamahub]
contains_example = false
import_path = "llama_index.storage.kvstore.duckdb"

[tool.llamahub.class_authors]
DuckDBKVStore = "llama-index"

[tool.mypy]
disallow_untyped_defs = true
exclude = ["_static", "build", "examples", "notebooks", "venv"]
ignore_missing_imports = true
python_version = "3.9"

[tool.pytest.ini_options]
addopts = "-s"  # disable captures
